### ISSUE TITLE
ZPure strange scenario blows with ClassCastException

### ISSUE THREAD

**Issue by atnoya** [zio/zio-prelude#496]
I apologize in advance because I am not I am not sure how to describe the issue better. 

I wrote a simplified version of my code that exemplifies the issue.

See:
```scala

import zio.prelude.fx.ZPure
type T[R, A] = ZPure[String, String, R, Nothing, A]

val useBothResults: ZPure[String, String, (Int, String), Nothing, String] =
  ZPure.environment[String, (Int, String)].map { case (theInt, theString) =>
    (theString.length * theInt).toString()
  }

val useBothResults2: ZPure[String, String, (Int, String), Nothing, String] =
  ZPure.access[(Int, String)] { case (theInt, theString) =>
    (theString.length * theInt * 2).toString()
  }
val theIntReader    = ZPure.environment[String, String].map(_.length())
val theStringReader = ZPure.environment[String, String].map(identity)

val theIntReader2    = ZPure.environment[String, String].map(_.length())
val theStringReader2 = ZPure.environment[String, String].map(identity)

val combined: ZPure[String, String, String, Nothing, String]  = (theIntReader <*> theStringReader) >>> useBothResults
val combined2: ZPure[String, String, String, Nothing, String] = (theIntReader2 <*> theStringReader2) >>> useBothResults2

val sequenced = combined.flatMap(_ => combined2)

def runComb = combined.provide("reader").runResult("state")
def runSeq  = sequenced.provide("reader").runResult("state")
```

If you run `runComb` it works fine, however, if you run `runSeq` it blows with:

```
java.lang.ClassCastException: scala.Tuple2 incompatible with java.lang.String
  at $Lambda$117930/0x000000009a8d5620.apply(Unknown Source)
  at zio.prelude.fx.ZPure.$anonfun$map$1(ZPure.scala:241)
  at zio.prelude.fx.ZPure$$Lambda$13651/000000000000000000.apply(Unknown Source)
  at zio.prelude.fx.ZPure.runEither(ZPure.scala:345)
  at zio.prelude.fx.ZPure.runEither$(ZPure.scala:292)
  at zio.prelude.fx.ZPure$Provide.runEither(ZPure.scala:597)
  at zio.prelude.fx.ZPure.run(ZPure.scala:286)
  at zio.prelude.fx.ZPure.run$(ZPure.scala:285)
  at zio.prelude.fx.ZPure$Provide.run(ZPure.scala:597)
  at zio.prelude.fx.ZPure.runResult(ZPure.scala:386)
  at zio.prelude.fx.ZPure.runResult$(ZPure.scala:385)
  at zio.prelude.fx.ZPure$Provide.runResult(ZPure.scala:597)
  at runSeq(<pastie>:25)
  ... 37 elided
```

zio-prelude version: `1.0.0-RC1`

**Comment by gurghet** [comment]
no idea what this is about, but copy-pasting this code and using the latest snapshot works.

**Comment by sideeffffect** [comment]
@atnoya can you try reproducing with the latest snapshot?
